USE [master]
GO

/****** Object:  Database [AdventureWorks2016]    Script Date: 2025/03/16 14:37:09 ******/
CREATE DATABASE [AdventureWorks2016]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AdventureWorks2016_Data', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\AdventureWorks2016_Data.mdf' , SIZE = 212608KB , MAXSIZE = UNLIMITED, FILEGROWTH = 16384KB )
 LOG ON 
( NAME = N'AdventureWorks2016_Log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\AdventureWorks2016_Log.ldf' , SIZE = 18432KB , MAXSIZE = 2048GB , FILEGROWTH = 16384KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AdventureWorks2016].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [AdventureWorks2016] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [AdventureWorks2016] SET ANSI_NULLS ON 
GO

ALTER DATABASE [AdventureWorks2016] SET ANSI_PADDING ON 
GO

ALTER DATABASE [AdventureWorks2016] SET ANSI_WARNINGS ON 
GO

ALTER DATABASE [AdventureWorks2016] SET ARITHABORT ON 
GO

ALTER DATABASE [AdventureWorks2016] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [AdventureWorks2016] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [AdventureWorks2016] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [AdventureWorks2016] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [AdventureWorks2016] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [AdventureWorks2016] SET CONCAT_NULL_YIELDS_NULL ON 
GO

ALTER DATABASE [AdventureWorks2016] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [AdventureWorks2016] SET QUOTED_IDENTIFIER ON 
GO

ALTER DATABASE [AdventureWorks2016] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [AdventureWorks2016] SET  DISABLE_BROKER 
GO

ALTER DATABASE [AdventureWorks2016] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [AdventureWorks2016] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [AdventureWorks2016] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [AdventureWorks2016] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [AdventureWorks2016] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [AdventureWorks2016] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [AdventureWorks2016] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [AdventureWorks2016] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [AdventureWorks2016] SET  MULTI_USER 
GO

ALTER DATABASE [AdventureWorks2016] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [AdventureWorks2016] SET DB_CHAINING OFF 
GO

ALTER DATABASE [AdventureWorks2016] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [AdventureWorks2016] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [AdventureWorks2016] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [AdventureWorks2016] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [AdventureWorks2016] SET QUERY_STORE = OFF
GO

USE [AdventureWorks2016]
GO

EXEC [AdventureWorks2016].sys.sp_addextendedproperty @name=N'MS_Description', @value=N'AdventureWorks 2016 Sample OLTP Database' 
GO

USE [master]
GO

ALTER DATABASE [AdventureWorks2016] SET  READ_WRITE 
GO


