USE [AdventureWorks2016]
GO
ALTER INDEX [IX_WorkOrder_ProductID] ON [Production].[WorkOrder] REBUILD PARTITION = ALL WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO
