GRANT UPDATE ON SCHEMA::Sales TO [LAPTOP-OKDI7SQH\Karabo Tsaoane]

EXECUTE AS USER ='LAPTOP-OKDI7SQH\Karabo Tsaoane';
SELECT *FROM fn_my_permissions ('Sales' ,'SCHEMA')
REVERT;
GO

REVOKE CONTROL ON SCHEMA::Sales TO [LAPTOP-OKDI7SQH\Karabo Tsaoane]