SELECT * 
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS 
WHERE TABLE_NAME = 'Client' AND CONSTRAINT_TYPE = 'UNIQUE';

ALTER TABLE dbo.Client
DROP CONSTRAINT UQ__Client__65800DA03D8BEAB9;

ALTER TABLE dbo.Client
ADD CONSTRAINT UQ__Client__65800DA03D8BEAB9 UNIQUE (ClientName);

select* from  dbo.Client;

DELETE FROM Client;
