name: Database Automation Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-db:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Removed: pip install sqlite3 (not needed)

      - name: Create and populate database
        run: |
          python create_db.py

      - name: Upload database artifact
        uses: actions/upload-artifact@v4
        with:
          name: AutoTest.db
          path: AutoTest.db

      - name: Deploy to server
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
        run: |
          echo "Deploying to server..."
          # sshpass -p $SERVER_PASSWORD scp AutoTest.db $SERVER_USER@$SERVER_IP:/path/to/destination/
