
name: First WorkFlow
on: workflow_dispatch

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print goodbye
        run: echo "Done - bye"
      
      - name: Print goodbye
        run: echo "Done - bye"

      
      
