name: Push HTML File to GitHub

# Trigger the workflow on push events to the main branch
on:
  push:
    branches:
      - main

jobs:
  push_html:
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Git
    - name: Set up Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    # Step 3: Add your HTML file (or any changes) to the repository
    - name: Add and commit HTML file
      run: |
        git add DatabaseAdministration/index.html
        git commit -m "Add simple HTML page"
      
    # Step 4: Push the changes to GitHub
    - name: Push changes
      run: git push origin main
