name: Python CI

on:
  push:
    branches:
      - main
    paths:
      - '**/*.py'               # Trigger on Python script changes
      - '**/requirements.txt'   # Trigger on changes to requirements file
      - '**/Pipfile'             # Trigger on Pipfile changes (if using pipenv)
      - '**/Dockerfile'          # Trigger on Dockerfile changes (if relevant)
      - '**/pyproject.toml'      # Trigger on changes to PyProject (if using Poetry)
  pull_request:
    branches:
      - main
    paths:
      - '**/*.py'               # Trigger on Python script changes
      - '**/requirements.txt'   # Trigger on changes to requirements file
      - '**/Pipfile'             # Trigger on Pipfile changes (if using pipenv)
      - '**/Dockerfile'          # Trigger on Dockerfile changes (if relevant)
      - '**/pyproject.toml'      # Trigger on changes to PyProject (if using Poetry)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.2'  # Adjust this to your Python version

      # Add any other steps you want, such as running tests, linting, etc.

    
