name: Run SQL Script

on: 
  push:
    branches:
      - main  # Runs when code is pushed to the main branch
  workflow_dispatch: # Allows manual execution

jobs:
  run-sql:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install & Start PostgreSQL
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql
          sudo systemctl start postgresql
          sudo systemctl status postgresql


      - name: Run SQL Script
        run: |
          PGPASSWORD=password psql -U postgres -d testdb -h localhost -f script.sql
