jobs:
   execute-sql:
     runs-on: ubuntu-latest
      steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install SQLCMD
        run: |
          sudo apt-get update
          sudo apt-get install -y mssql-tools unixodbc-dev
      - name: Run SQL script
        run: >
          sqlcmd -S your_server.database.windows.net -d StudentDB -U
          your_username -P your_password -i Select_student.sql
