name: Run SQL Script

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  execute-sql:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install SQLCMD
        run: choco install sqlcmd -y

      - name: Run SQL Script
        run: |
          sqlcmd -S LAPTOP-OKDI7SQH -d StudentDB -E -i "C:\sc_KaraboTsaoane_2025\DataAdministration\SQLStatements\Select_student.sql"
