name: SQL Server Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Microsoft SQL Server Tools
        shell: pwsh
        run: |
          # Set the SQLCMD Installer URL (EXE)
          $url = "https://aka.ms/sqlcmdlinux"
          $installer = "sqlcmd_installer.exe"
          $outputDir = "C:\sqlcmd-tools"

          # Download SQLCMD installer
          Write-Host "Downloading SQLCMD installer..."
          Invoke-WebRequest -Uri $url -OutFile $installer

          # Install SQLCMD silently
          Write-Host "Installing SQLCMD..."
          Start-Process -FilePath $installer -ArgumentList "/quiet", "/install" -Wait

          # Remove the installer after installation
          Remove-Item -Path $installer -Force

          # Add SQLCMD path to environment variable
          echo "C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn" | Out-File -Append -Encoding utf8 $env:GITHUB_PATH



      - name: Run SQL script
        env:
          SQL_SERVER_HOST: https://whole-cobras-start.loca.lt
          SQL_SERVER_USER: AutoUser
          SQL_SERVER_PASSWORD: ${{ secrets.SQL_SERVER_PASSWORD }}
        run: |
          sqlcmd -S ${SQL_SERVER_HOST} -U ${SQL_SERVER_USER} -P ${SQL_SERVER_PASSWORD} -Q "USE AutoTest; INSERT INTO [user] ([name], [surname], [email]) VALUES ('John', 'Doe', 'john.doe@example.com');"
