name: SQL Server Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Microsoft SQL Server Tools
        shell: powershell
        run: |
          $url = "https://aka.ms/go-sqlcmd-windows"
          $output = "sqlcmd.zip"

          # Download with retry logic
          $maxRetries = 3
          $retryDelay = 5
          $success = $false
          for ($i=1; $i -le $maxRetries; $i++) {
              Write-Host "Attempt $i: Downloading SQLCMD..."
              curl.exe -L -o $output $url
              
              # Check if the file is a valid ZIP
              if (Test-Path $output -PathType Leaf) {
                  try {
                      Expand-Archive -Path $output -DestinationPath "C:\sqlcmd-tools" -ErrorAction Stop
                      $success = $true
                      break
                  } catch {
                      Write-Host "Downloaded file is invalid. Retrying in $retryDelay seconds..."
                      Start-Sleep -Seconds $retryDelay
                  }
              }
          }

          if (-not $success) {
              throw "Failed to download a valid sqlcmd.zip file after multiple attempts."
          }

          echo "C:\sqlcmd-tools" | Out-File -Append -Encoding utf8 $env:GITHUB_PATH




      - name: Run SQL script
        env:
          SQL_SERVER_HOST: https://whole-cobras-start.loca.lt
          SQL_SERVER_USER: AutoUser
          SQL_SERVER_PASSWORD: ${{ secrets.SQL_SERVER_PASSWORD }}
        run: |
          sqlcmd -S ${SQL_SERVER_HOST} -U ${SQL_SERVER_USER} -P ${SQL_SERVER_PASSWORD} -Q "USE AutoTest; INSERT INTO [user] ([name], [surname], [email]) VALUES ('John', 'Doe', 'john.doe@example.com');"
