name: SQL Server Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Microsoft SQL Server Tools
        run: |
          Invoke-WebRequest -Uri https://aka.ms/go-sqlcmd-windows -OutFile sqlcmd.zip
          Expand-Archive -Path sqlcmd.zip -DestinationPath "C:\sqlcmd-tools"
          echo "C:\sqlcmd-tools" | Out-File -Append -Encoding utf8 $env:GITHUB_PATH


      - name: Run SQL script
        env:
          SQL_SERVER_HOST: https://whole-cobras-start.loca.lt
          SQL_SERVER_USER: AutoUser
          SQL_SERVER_PASSWORD: ${{ secrets.SQL_SERVER_PASSWORD }}
        run: |
          sqlcmd -S ${SQL_SERVER_HOST} -U ${SQL_SERVER_USER} -P ${SQL_SERVER_PASSWORD} -Q "USE AutoTest; INSERT INTO [user] ([name], [surname], [email]) VALUES ('John', 'Doe', 'john.doe@example.com');"
