name: SQL Server Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download and install sqlcmd
        run: |
          # Download the SQLCMD zip file using WebClient
          $webClient = New-Object System.Net.WebClient
          $webClient.DownloadFile("https://aka.ms/go-sqlcmd-windows", "sqlcmd.zip")
          
          # Extract the zip file
          Expand-Archive -Path sqlcmd.zip -DestinationPath "sqlcmd"

          # Clean up the zip file after extraction
          Remove-Item sqlcmd.zip

      - name: Run SQL script
        env:
          SQL_SERVER_HOST: https://your-url.loca.lt
          SQL_SERVER_USER: AutoUser
          SQL_SERVER_PASSWORD: ${{ secrets.SQL_SERVER_PASSWORD }}
        run: |
          # Add sqlcmd folder to the PATH temporarily
          $env:PATH = "$env:PATH;$(Build.ArtifactStagingDirectory)\sqlcmd\sqlcmd"

          # Run the SQL script using sqlcmd
          sqlcmd.exe -S ${SQL_SERVER_HOST} -U ${SQL_SERVER_USER} -P ${SQL_SERVER_PASSWORD} -Q "USE AutoTest; INSERT INTO [user] ([name], [surname], [email]) VALUES ('John', 'Doe', 'john.doe@example.com');"
